<h2><font color="#004D7F" size=6>Visualizaci√≥n de Datos uso de DAsH</font></h2>



<br><br>
<div style="text-align: right">
<font color="#004D7F" size=3>Danyela Luengas</font><br>
<font color="#004D7F" size=3>Graficos con Python</font><br>

In [1]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image, ImageDraw
from matplotlib import style
import matplotlib.ticker as ticker
import seaborn as sns
import pandas as pd


import plotly 

plotly.__version__

'5.4.0'

In [2]:
!pip install -q plotly==5.4 dash jupyter-dash

In [3]:
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
from jupyter_dash import JupyterDash
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio

C:\Users\daalu\AppData\Local\Temp\ipykernel_6596\2408339184.py:2: UserWarning:
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc
C:\Users\daalu\AppData\Local\Temp\ipykernel_6596\2408339184.py:3: UserWarning:
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html

In [4]:
wb_data=px.data.gapminder()
wb_data.head(30)

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4
5,Afghanistan,Asia,1977,38.438,14880372,786.113360,AFG,4
6,Afghanistan,Asia,1982,39.854,12881816,978.011439,AFG,4
7,Afghanistan,Asia,1987,40.822,13867957,852.395945,AFG,4
8,Afghanistan,Asia,1992,41.674,16317921,649.341395,AFG,4
9,Afghanistan,Asia,1997,41.763,22227415,635.341351,AFG,4
10,Afghanistan,Asia,2002,42.129,25268405,726.734055,AFG,4
11,Afghanistan,Asia,2007,43.828,31889923,974.580338,AFG,4
12,Albania,Europe,1952,55.230,1282697,1601.056136,ALB,8
13,Albania,Europe,1957,59.280,1476505,1942.284244,ALB,8
14,Albania,Europe,1962,64.820,1728137,2312.888958,ALB,8
15,Albania,Europe,1967,66.220,1984060,2760.196931,ALB,8
16,Albania,Europe,1972,67.690,2263554,3313.422188,ALB,8
17,Albania,Europe,1977,68.930,2509048,3533.003910,ALB,8
18,Albania,Europe,1982,70.420,2780097,3630.880722,ALB,8
19,Albania,Europe,1987,72.000,3075321,3738.932735,ALB,8
20,Albania,Europe,1992,71.581,3326498,2497.437901,ALB,8
21,Albania,Europe,1997,72.950,3428038,3193.054604,ALB,8
22,Albania,Europe,2002,75.651,3508512,4604.211737,ALB,8
23,Albania,Europe,2007,76.423,3600523,5937.029526,ALB,8
24,Algeria,Africa,1952,43.077,9279525,2449.008185,DZA,12
25,Algeria,Africa,1957,45.685,10270856,3013.976023,DZA,12
26,Algeria,Africa,1962,48.303,11000948,2550.816880,DZA,12
27,Algeria,Africa,1967,51.407,12760499,3246.991771,DZA,12
28,Algeria,Africa,1972,54.518,14760787,4182.663766,DZA,12
29,Algeria,Africa,1977,58.014,17152804,4910.416756,DZA,12

In [5]:
# se crea la aplicaci√≥n
app  =JupyterDash(__name__)
app.title='banco mundial de datos'

In [6]:
title=html.H1('Banco Mundial de Datos') # crea el titulo de la pagina

In [7]:
scatter_header=html.H4('GDP and life expentancy evolution by region ')

In [8]:
fig=px.scatter(wb_data, x='gdpPercap', y='lifeExp', size='pop', color='continent', animation_frame='year',
              hover_name='country', range_y=[20,90], size_max=60, log_x=True)

In [9]:
#@app.callback(Output("scatter-graph", "figure"), [Input("scatter-dropdown", "value")])                                                      

def select_region(region):
    if region:
        subset =wb_data.query(f"continent == '{region}'")
    else:
        subset =wb_data
        
    fig=px.scatter(subset, x='gdpPercap', y='lifeExp', size='pop', color='continent', animation_frame='year',
              hover_name='country', range_y=[20,90], size_max=60, log_x=True)
    return fig
#se crea un grafica

In [10]:


scatter_dropdown =dcc.Dropdown(
   # id='scatter-dropdown',
    options=[
            {'label':'wordwide', 'value': ''},
            {'label':'Asia', 'value': 'Asia'},
            {'label':'Americas', 'value': 'Americas'},
            {'label':'Europe', 'value': 'Europe'},
            {'label':'Africa', 'value': 'Africa'},
            {'label':'Ocean√≠a', 'value': 'Ocean√≠a'}
    ],
    value=''
)

In [11]:
# meter la grafica creada  a la p√°gina web
scatter_graph =dcc.Graph(figure=fig)
#scatter_graph =dcc.Graph(id='scatter-graph')

In [12]:
scatter_row = html.Div(
    children=[
              scatter_header,
              scatter_dropdown,
              scatter_graph      
    ]
)

In [13]:
 # cargar el  aplicativo web

In [14]:
map_header =html.H4('evolutcion por pais')

In [15]:
@app.callback(Output('map-graph', 'figure'), [Input('map-radio', 'value')])
def select_metric(metric):
    fig= px.choropleth(wb_data, locations='iso_alpha', color=metric,
                   animation_frame='year',  hover_name='country' )

In [16]:
map_radio =dcc.RadioItems(
    id='map-radio',
    options=[
            {'label':'GDP per capita', 'value': 'gdpPercap'},
            {'label':'Life expectancy', 'value': 'lifeExp'},
            {'label':'Population', 'value': 'pop'}
            
    ],
    value ='gdpPercap'

)

In [17]:
map_graph =dcc.Graph(id='map-graph')

In [18]:
map_row = html.Div(
    children=[
              map_header,
              map_radio,
              map_graph
        
    ]


)

In [19]:
app.layout =html.Div(
    children=[
              title,
              scatter_row,
               map_row
    ]

) # la aplicacion tiene duse√±o

In [21]:
app.run_server(debug=True, mode='inline')